In [ ]:
print("hi this is sujith")


hi this is sujith


In [ ]:
import numpy as np

In [ ]:
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [ ]:
print(arr.shape)
print(arr.ndim)

(5,)
1


In [ ]:
print(type(arr))

<class 'numpy.ndarray'>


In [ ]:
arr1 = np.array(56)

In [ ]:
print(arr1)
print(arr1.shape)
print(arr1.ndim)

56
()
0


In [ ]:
arr2 = np.array([[1,2,3],[4,7,9]])
print(arr2)

[[1 2 3]
 [4 7 9]]
[[1 2 3]
 [4 7 9]]


In [ ]:
print(arr2.shape)
print(arr2.ndim)

(2, 3)
2


In [ ]:
arr3 = np.array([[[1,2,3],[4,7,9]],[[1,2,3],[4,7,9]]])
print(arr3)
print(arr3.shape)
print(arr3.ndim)

[[[1 2 3]
  [4 7 9]]

 [[1 2 3]
  [4 7 9]]]
(2, 2, 3)
3


In [ ]:
arr4 = np.array([1, 2, 3, 4 ,5], ndmin=5)
print(arr4)
print(arr4.shape)
print('number of dimensions:', arr4.ndim)

[[[[[1 2 3 4 5]]]]]
(1, 1, 1, 1, 5)
number of dimensions: 5


In [ ]:
print(arr1,arr[0],arr2[0][1],arr3[0][1][2])

56 1 2 9


In [ ]:
print(arr2)
print(arr2[-2, -1])

[[1 2 3]
 [4 7 9]]
3


In [ ]:
arr4 = np.array([1,2,3,4,5,6,7,8])
print(arr4[1:5])
print(arr4[-5:-1])
print(arr4[2:])
print(arr4[:4])

[2 3 4 5]
[4 5 6 7]
[3 4 5 6 7 8]
[1 2 3 4]


In [ ]:
import numpy as np


In [ ]:
arr6 = np.array(['apple', 'banana', 'cherry'])

print(arr6.dtype)

<U6


In [ ]:
arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [ ]:
arr = np.array([3.47, 2.14, 4.15])

newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)

[3 2 4]
int32


In [ ]:
arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [ ]:
import numpy as np

arr= np.array([1, 2, 3, 4, 5])

x = arr.copy() 
arr[0] = 42

print(arr)

print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]) 
newarr = arr.reshape(2, 3, 2)

print(newarr)


[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [ ]:

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  for y in x:
    print(y)

1
2
3
4
5
6


In [ ]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)

print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [ ]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [ ]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))

print(arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 4)

print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [ ]:
import numpy as np

In [ ]:
arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
n =int(input("enter the number\n"))
a=0
b=1
c=1
if (n==0 or n==1):
  print("true")
else:
  while c<n:
    c=a+b
    b=a
    a=c
  if(c==n):
    print("true")
  else:
    print("false")

enter the number
10
false


In [ ]:
l =int(input("enter the number\n"))
u =int(input("enter the number\n"))

print("Prime numbers between", l, "and", u, "are:")

for num in range(l, u + 1):
   
   if num > 1:
       for i in range(2, num):
           if (num % i) == 0:
               break
       else:
           print(num)

enter the number
5
enter the number
44
Prime numbers between 5 and 44 are:
5
7
11
13
17
19
23
29
31
37
41
43
