In [ ]:

 import numpy as np
 np.random.randint(1, 5, size=(4, 5))

array([[2, 4, 2, 3, 4],
       [4, 2, 2, 4, 3],
       [1, 1, 1, 2, 3],
       [3, 3, 3, 2, 2]])

In [ ]:
from numpy import random
arr = random.randint(8,size=(1,4))
print("Original Array : \n",arr)
newarr =  arr.reshape(2,2)
print("\nConvert it to a 2D array with 2 rows : \n",newarr)


Original Array : 
 [[7 0 3 5]]

Convert it to a 2D array with 2 rows : 
 [[7 0]
 [3 5]]


In [ ]:
import numpy as np
fvalues = [0, 15, 66.21, 24, 91.91, 42]
F = np.array(fvalues)
print("Values in Fahrenheit degrees:")
print(F)
print("Values in  Centigrade degrees:")
print(np.round((5*F/9 - 5*32/9),2))

Values in Fahrenheit degrees:
[ 0.   15.   66.21 24.   91.91 42.  ]
Values in  Centigrade degrees:
[-17.78  -9.44  19.01  -4.44  33.28   5.56]


In [ ]:
arr = np.array([1,5,6,7,8])
print(arr)
print("no of Dimensions : ",arr.ndim)
print("no of Elements : ",arr.size)
print("no of Bytes : ",arr.itemsize)

[1 5 6 7 8]
no of Dimensions :  1
no of Elements :  5
no of Bytes :  8


In [ ]:
ar = random.randint(8,size=(3,4))
print(ar)
print("Extract third and fourth elements from second and third row : ")
print(ar[1:3,2:4])

[[5 5 6 4]
 [7 3 7 4]
 [3 6 5 0]]
Extract third and fourth elements from second and third row : 
[[7 4]
 [5 0]]


In [ ]:
ur = int(input("Enter the Number : "))
a,b,l=0,1,0
next=0
for i in range(num+1): # 0,1,1,2,3,5,8,13,21,34,..............
  next=a+b
  a=b
  b=next
  if next==num:
    print("It's a Fibonacci Number")
    l=1
    break
if(l!=1):
  print("It's not a Fibonacci Number")

Enter the Number : 55


NameError: ignored

In [ ]:
array = list(map(int,input("Enter array : ").split()))
p = int(input("Enter kth position : "))
u=[]
for t in range(p-1,len(array)):
  u.append(array[t])
for t in range(0,p-1):
  u.append(array[t])
print(u)

Enter array : 2 6 7 8
Enter kth position : 2
[6, 7, 8, 2]


In [ ]:
t=input("Enter the digit : ")
num=int(input("Enter the num : "))
s=0
for i in t:
  if int(i)%num==0:
    s+=1
if s==len(t):
  print("all numbers are divisible by the given num")
else:
  print("Can't divide")

Enter the digit : 44
Enter the num : 23
Can't divide


In [ ]:
m = int(input("Enter the Number : "))
a,b,l=0,1,0
next=0
for i in range(num+1): # 0,1,1,2,3,5,8,13,21,34,..............
  next=a+b
  a=b
  b=next
  if next==num:
    print("It's a Fibonacci Number")
    l=1
    break
if(l!=1):
  print("It's not a Fibonacci Number")

Enter the Number : 33
It's not a Fibonacci Number


In [ ]:
v= list(map(int,input("Enter the range(Ex : 2 14) : ").split()))
x=[]
if(v[0]<v[1]):
  for i in range(v[0],v[1]+1):
    if i>1:
      for j in range(2,int(i/2)+1):
        if((i%j)==0):
          break
      else:
        x.append(i)
print(x)

Enter the range(Ex : 2 14) : 3 13
[3, 5, 7, 11, 13]
